# Generated by Django 3.2.3 on 2021-06-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_data',
            name='com_cn',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
