# Generated by Django 3.2.3 on 2021-06-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_company_data_com_cn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_data',
            old_name='com_cn',
            new_name='com_cno',
        ),
    ]
