# Generated by Django 4.0.2 on 2022-03-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_com_cn_company_data_com_cno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company_data',
            new_name='User_data',
        ),
    ]
